#page title
page_title                                : Sip

# App Info
ios_app_id                                : 6444360091                                
ios_app_country                           : ch                                        

appstore_link                             :                                           
playstore_link                            :                                           
presskit_download_link                    : https://getsip.app/assets/presskit.zip    
                                                                                      

app_icon                                  : assets/appicon.png                        
app_name                                  : Sip - Collect & Enjoy Wine                
app_price                                 :                                           
app_description                           : Everything you need to track your cellar, find your bottles, and bring your collection to life.

enable_smart_app_banner                   : true                                      



# Information About Yourself
your_name                                 : Roman Blum                                
your_link                                 : 
your_city                                 : Zurich                                
email_address                             : hello@getsip.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : getsipapp
github_username                           : rmnblm
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Cellar Management
    description                           : Keep track of the wines in your cellar, including information such as wine name, vintage, producer, region, and price. Search, filter and get the most out of your cellar.
    fontawesome_icon_name                 : wine-bottle
    
  - title                                 : Tasting Journal
    description                           : Write tasting notes and rate your wines on a scale from 1 to 5 stars.
    fontawesome_icon_name                 : pencil

  - title                                 : Dark Mode Support
    description                           : In addition to the gorgeous Light Mode, Apollo also has an incredible Dark Mode that's great when you want something easier on your eyes at night, or you just prefer Dark Modes.
    fontawesome_icon_name                 : adjust

  - title                                 : Native Speed, Beautiful UI
    description                           : Sip was built from the beginning to look and feel like a gorgeous, immediately familiar iOS app, following the design guidelines Apple put forward. 
    fontawesome_icon_name                 : magic

  - title                                 : Import and Export
    description                           : Import your collections from or to an Excel sheet.
    fontawesome_icon_name                 : table
  
  - title                                 : iCloud Sync
    description                           : Your data will be stored in your iCloud account. You can disable this at any time from your settings.
    fontawesome_icon_name                 : cloud
  
  - title                                 : iPhone & iPad
    description                           : Enjoy Sip not only on your iPhone, but also on your iPad. A future update will bring Sip to Mac too.
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#0396FF"
feature_icons_background_color            : "#ABDCFF"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
